### ISSUE TITLE
Please specify in the User Manual how to download programs from Linux and Mac

### ISSUE THREAD

**Issue by rlcarr** [bradsprojects/Digirule2U#3]
There is a Mac program download utility but none for Windows and Linux.

Please say in the User Manual how to download programs from a Windows or Linux computer into the Digirule (even if it's just "cat the .hex file to the serial port".  If programs cannot be downloaded from Windows or Mac until a download utility is released in the future, please say that.

**Comment by kd0gls** [comment]
Hi rlcarr,

The "dldr2" utility is not provided for Linux or Windows simply because its sole purpose is to work around a problem that is unique to the Mac command line.  On Linux and Windows the standard command-line redirection mechanism works as expected without the need for assistance from an external utility.  And if you use a terminal emulator program to perform your transfers, there's no need for the utility at all, even on Mac.

We have declined at this time to document any one particular command or mechanism for transferring data between the operating system and the serial device to which the Digirule 2U is attached, simply because the ways in which this can be accomplished are many and better documented elsewhere.
